extends Node
## Persistent, scene-reactive ambient music. Each view gets its own soothing pad
## (generated by tools/gen_audio.gd); on every scene swap Music crossfades to the
## matching track so audio shifts with the scene without ever cutting out. Lives in
## an autoload so it survives transitions and keeps playing while the tree is paused.

const VOLUME_DB: float = -14.0
const MUTED_DB: float = -60.0
const FADE: float = 0.8

# Scene path -> ambient track. Scenes not listed keep the current track.
const SCENE_TRACKS := {
	"res://scenes/ui/title_screen.tscn": "res://assets/audio/ambient_title.tres",
	"res://scenes/external/task_board.tscn": "res://assets/audio/ambient_board.tres",
	"res://scenes/external/external_world.tscn": "res://assets/audio/ambient_world.tres",
	"res://scenes/internal/internal_mind.tscn": "res://assets/audio/ambient_mind.tres",
	"res://scenes/ui/day_end_summary.tscn": "res://assets/audio/ambient_dayend.tres",
	"res://scenes/ui/ending.tscn": "res://assets/audio/ambient_ending.tres",
	"res://scenes/ui/codex.tscn": "res://assets/audio/ambient_dayend.tres",
}
const BOOT_TRACK: String = "res://assets/audio/ambient_title.tres"   # main scene = title

var _players: Array[AudioStreamPlayer] = []
var _active: int = 0                 # index of the currently-audible player
var _current_track: String = ""
var _muted: bool = false


func _ready() -> void:
	# Keep playing while the tree is paused (the Esc overlay pauses everything else),
	# otherwise the ambient track silences itself and the Sound toggle looks dead.
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in 2:
		var p := AudioStreamPlayer.new()
		p.volume_db = MUTED_DB
		add_child(p)
		_players.append(p)
	_play_track(BOOT_TRACK, true)
	EventBus.scene_changed.connect(_on_scene_changed)


func _on_scene_changed(scene_path: String) -> void:
	var track: String = SCENE_TRACKS.get(scene_path, "")
	if track != "":
		_play_track(track, false)


## Play a specific track for the current situation, overriding the scene-mapped one.
## Falls back gracefully if the file is missing (keeps the current ambience).
func play_for_situation(track_path: String) -> void:
	if track_path == "" or not ResourceLoader.exists(track_path):
		return
	_play_track(track_path, false)


## Crossfade the active player out and a fresh one in (or hard-cut on boot).
func _play_track(track_path: String, instant: bool) -> void:
	if track_path == _current_track:
		return
	_current_track = track_path
	var stream: AudioStream = load(track_path)
	if stream == null:
		push_error("Music: missing track %s" % track_path)
		return

	var old: AudioStreamPlayer = _players[_active]
	_active = 1 - _active
	var cur: AudioStreamPlayer = _players[_active]

	cur.stream = stream
	cur.play()
	var target: float = MUTED_DB if _muted else VOLUME_DB
	if instant:
		cur.volume_db = target
		old.stop()
		return
	_fade(cur, target)
	_fade(old, MUTED_DB)


func _fade(player: AudioStreamPlayer, to_db: float) -> void:
	var tween := create_tween()
	tween.tween_property(player, "volume_db", to_db, FADE)


func set_muted(muted: bool) -> void:
	_muted = muted
	var target: float = MUTED_DB if muted else VOLUME_DB
	_fade(_players[_active], target)
